name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Compile
        run: |
          javac -d bin \
            src/exceptions/*.java \
            src/model/collectibles/*.java \
            src/model/world/*.java \
            src/model/characters/*.java \
            src/engine/*.java
      - name: Run Tests
        run: |
          javac -cp bin:. -d bin src/tests/*.java
          java -cp bin:. org.junit.runner.JUnitCore tests.M1PublicTests tests.M2PublicTests
